### ISSUE TITLE
Update composer.json

### ISSUE THREAD

**Issue by discordier** [respinar/contao-jalalidate#1]
You should update your composer.json to indicate that it is of type "contao-module" and also add an requirement on "contao-community-alliance/composer-plugin" in (at least) version 2.0 to ensure correct installation of your extension in Contao.
Sorry that our docs are a bit vague about this.

For a more complex example, check https://github.com/contao-community-alliance/dc-general/blob/develop/composer.json or other repositories of Contao extensions.

**Comment by hamidpeywasti** [comment]
Thank you. I did them.
